name: internet_connectivity_checker
description: The flutter package that helps you easily manage widgets dynamically based on the device's internet access.
version: 1.0.1
homepage: https://github.com/csof3cen/internet_connectivity_checker

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: